
# Site settings
title: João Vitor F. Cavalcante
email: jvfecav@gmail.com
description: Programmer ⏺ Bioinformatician
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 
city: Natal
state: RN
zip_code: 
country: Brazil
phone: 

icon:  # Font Awesome class for your site's icon

# Social settings
facebook_url:
github_url: https://github.com/jvfe
gitlab_url: https://gitlab.com/jvfe
googleplus_url: 
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/Jvcavv

# Build settings
markdown: kramdown

sass:
style: compressed
